n = int(input('Digite um número inteiro para saber a sua tabuada: '))
print('=' * 14)
print('{} x {:2} = {}'.format(n, 0, n*0))
print('{} x {:2} = {}'.format(n, 1, n*1))
print('{} x {:2} = {}'.format(n, 2, n*2))
print('{} x {:2} = {}'.format(n, 3, n*3))
print('{} x {:2} = {}'.format(n, 4, n*4))
print('{} x {:2} = {}'.format(n, 5, n*5))
print('{} x {:2} = {}'.format(n, 6, n*6))
print('{} x {:2} = {}'.format(n, 7, n*7))
print('{} x {:2} = {}'.format(n, 8, n*8))
print('{} x {:2} = {}'.format(n, 9, n*9))
print('{} x {:2} = {}'.format(n, 10, n*10))
print('=' * 14)
'''
n0 = n * 0
n1 = n * 1
n2 = n * 2
n3 = n * 3
n4 = n * 4
n5 = n * 5
n6 = n * 6
n7 = n * 7
n8 = n * 8
n9 = n * 9
n10 = n * 10
print('{} x {} = {}'.format(n, 0, n0))
print('{} x {} = {}'.format(n, 1, n1))
print('{} x {} = {}'.format(n, 2, n2))
print('{} x {} = {}'.format(n, 3, n3))
print('{} x {} = {}'.format(n, 4, n4))
print('{} x {} = {}'.format(n, 5, n5))
print('{} x {} = {}'.format(n, 6, n6))
print('{} x {} = {}'.format(n, 7, n7))
print('{} x {} = {}'.format(n, 8, n8))
print('{} x {} = {}'.format(n, 9, n9))
print('{} x {} = {}'.format(n, 10, n10))
'''