n = input('Digite algo: ')
print('O tipo primitivo é {}'.format(type(n)))
print('É um número? {}'.format(n.isnumeric()))
print('É alfanumérico? {}'.format(n.isalnum()))
print('É alfabéfico? {}'.format(n.isalpha()))
print('É decimal? {}'.format(n.isdecimal()))
print('Está tudo em minúsculo? {}'.format(n.islower()))
print('Só tem espaços? {}'.format(n.isspace()))
print('Está capitalizada? {}'.format(n.istitle()))
print('Está tudo em maiúsculo? {}'.format(n.isupper()))
