nome = input('Informe seu nome: ')  # .strip()
print(nome.upper())
print(nome.lower())
print(len(''.join(nome.split())))
# print(len(nome) - nome.count(' ')))
dividido = nome.split()
print(len(dividido[0]))
